### PR TITLE
fix!: throw an error when the source account has low balance

### LINKED ISSUE #338: Using the SDK when trying to send a value higher than the balance is allowed
**Context**: While using the SDK https://github.com/sygmaprotocol/sygma-sdk/blob/main/examples/evm-to-evm-fungible-transfer/src/transfer.ts to transfer Fungible token EVM to EVM, of a token that is also the FEE, for a value that is > actual balance, it is allowed.

**STR**:
1. Have a wallet on source with 1000 sygUSDC.
2. Use the SDK to transfer 1500 sygUSDC to another compatible destination.

**Expectancy**: 
The TX should be discarded from the beginning as the the transfer value of 1500 is higher than the actual balance.

**Actual**:
The TX is emitted and fails after partial execution.
https://sepolia.etherscan.io/tx/0x25a6b39ae8ac84b945c3695212199f37c602ebf37d48ca1bf26bbfca84ac16cd

### PR DESCRIPTION
**Pull request by Lykhoyda**
Closes #338

### CODE REVIEW

File: packages/evm/src/fungible.ts [hunk 1]
```diff
@@ -197,6 +201,8 @@ class EvmFungibleAssetTransfer extends BaseTransfer {
     const bridge = Bridge__factory.connect(domainConfig.bridge, provider);
     const fee = await this.getFee();
 
+    await this.verifyAccountBalance(fee);
```
Comment (saadjhk) [inline packages/evm/src/fungible.ts:204]: I think its better to make this call in `isValidTransfer` as `getApprovalTransactions` also requires the account to be funded

Comment (Lykhoyda) [reply packages/evm/src/fungible.ts:206]: @saadjhk I'm thinking about where to put the validation and why I call the method later as I want to ensure the balance is correct before the on-chain interaction. I imagine that some User who will integrate our SDK and has a UI could create an instance of Fungible transfer, but make a call later. So the balance validation could be changed. Also to keep the principle of single responsibility for the method I would call it outside the "isValidTransfer" as this method makes sure that the provided combination of the source and destination data are valid with our config.

File: packages/substrate/src/fungible.ts [hunk 2]
```diff
@@ -94,21 +99,41 @@ class SubstrateFungibleAssetTransfer extends BaseTransfer {
...
+    }
+
+    const { data: balance } = (await this.sourceNetworkProvider.query.system.account(
+      this.senderAddress,
+    )) as unknown as {
+      data: AccountData;
+    };
+
+    // TODO: clarify if we extract fee from amount or add on top of it
+    const costs = new BN(this.amount.toString()).add(fee.fee);
```
Comment (Lykhoyda) [inline packages/substrate/src/fungible.ts:119]: @saadjhk @wainola Do you know for sure how the fee will be calculated here?

Comment (saadjhk) [reply packages/substrate/src/fungible.ts:119]: IMO `fee` is deducted from the user specified amount on substrate

c.c @MakMuftic @wainola

File: packages/evm/src/fungible.ts [hunk 3]
```diff
@@ -207,4 +215,18 @@ class EvmFungibleAssetTransfer extends BaseTransfer {
...
+  async verifyAccountBalance(fee: EvmFee): Promise<void> {
+    const provider = new Web3Provider(this.sourceNetworkProvider);
+    const erc20 = ERC20__factory.connect(this.resource.address, provider);
+    const balance = await erc20.balanceOf(this.sourceAddress);
+
+    // TODO: check cost calculation
+    let totalCost: BigNumber = BigNumber.from(this.amount);
+    if (fee.type === FeeHandlerType.PERCENTAGE) {
+      totalCost = totalCost.add(BigNumber.from(fee.fee));
+    }
```
Comment (Lykhoyda) [inline packages/evm/src/fungible.ts:228]: @saadjhk as we deduct the fee from the amount:
```ts
this._amount = calculateAdjustedAmount(this, fee);
```

To calculate the required balance I add the fee back to calculate the initial required amount to perform the transfer.

Comment (saadjhk) [reply packages/evm/src/fungible.ts:228]: @Lykhoyda should we not implement this feature for `basic` and `twap` type fee calculation?

Comment (saadjhk) [reply packages/evm/src/fungible.ts:228]: > @saadjhk as we deduct the fee from the amount:
> 
> ```ts
> this._amount = calculateAdjustedAmount(this, fee);
> ```
> 
> To calculate the balance I add the fee back to calculate the initial required amount to perform the transfer.

I didn't get this, what do you mean by add the fee back

Comment (Lykhoyda) [reply packages/evm/src/fungible.ts:228]: @saadjhk When we call calculateAdjustedAmount method in setAmount

```ts
async setAmount(amount: bigint): Promise<void> {
    this._amount = amount;
    const fee = await this.getFee();
    this._amount = calculateAdjustedAmount(this, fee);
  }
  ```
If the fee type is a percentage, then we subtract the fee from the "amount" specified by the user. But your account should have the balance with the same amount that you set when creating a transfer (without subtracting the fee).

Comment (Lykhoyda) [reply packages/evm/src/fungible.ts:228]: Maybe it makes sense to have two variables with amount:
transferAmount ( original value)
amountWithFee (after calculateAdjustedAmount call)

Comment (saadjhk) [reply packages/evm/src/fungible.ts]: `specifiedAmount` and `adjustedAmount`

File: packages/evm/src/fungible.ts [hunk 4]
```diff
@@ -95,18 +98,31 @@ export async function createEvmFungibleAssetTransfer(
...
-    return this._amount;
+    if (isValidAddressForNetwork(transfer.destinationAddress, this.destination.type))
+      this.destinationAddress = transfer.destinationAddress;
+    this.securityModel = transfer.securityModel ?? SecurityModel.MPC;
+  }
+
+  /**
+   * Returns amount to be transferred considering the fee
+   */
+  get adjustedAmount(): bigint {
```
Comment (saadjhk) [inline packages/evm/src/fungible.ts:116]: instead of having a `getAdjustAmount` getter can we have a simple `amount` getter, no need to provide context to end user I would say

File: packages/evm/src/fungible.ts [hunk 5]
```diff
@@ -199,4 +218,16 @@ class EvmFungibleAssetTransfer extends EvmTransfer {
...
     return createTransactionRequest(transferTx);
   }
+
+  async verifyAccountBalance(): Promise<void> {
+    const resource = this.resource as EvmResource;
+    const provider = new Web3Provider(this.sourceNetworkProvider);
+    const erc20 = ERC20__factory.connect(resource.address, provider);
+    const balance = await erc20.balanceOf(this.sourceAddress);
+
+    if (BigNumber.from(this.adjustedAmount).lte(0))
```
Comment (saadjhk) [inline packages/evm/src/fungible.ts:228]: there is a case when the balance needs to be present in `ETH` account when fee is deducted from `BASIC` or `TWAP` fee handler however, this only checks token balance

File: packages/evm/src/fungible.ts [hunk 6]
```diff
@@ -96,18 +98,31 @@ export async function createEvmFungibleAssetTransfer(
 class EvmFungibleAssetTransfer extends EvmTransfer {
   protected destinationAddress: string = '';
   protected securityModel: SecurityModel;
-  protected _amount: bigint;
+  protected _adjustedAmount: bigint = BigInt(0);
```
Comment (saadjhk) [inline packages/evm/src/fungible.ts:101]: can we name this variable just `adjustedAmount`

File: packages/evm/src/fungible.ts [hunk 7]
```diff
@@ -200,4 +214,27 @@ class EvmFungibleAssetTransfer extends EvmTransfer {
...
+    // Native Token Balance check
+    if ([FeeHandlerType.BASIC, FeeHandlerType.TWAP].includes(fee.type)) {
+      const nativeBalance = await provider.getBalance(this.sourceAddress);
+
+      if (nativeBalance.lt(fee.fee))
+        throw new Error(`Insufficient native token balance for network ${this.sourceDomain.name}`);
+    }
+
+    // ERC20 Token Balance check
+    if ([FeeHandlerType.BASIC, FeeHandlerType.PERCENTAGE].includes(fee.type)) {
```
Comment (saadjhk) [inline packages/evm/src/fungible.ts:231]:
```typescript
    if (FeeHandlerType.PERCENTAGE === fee.type) {
```

File: packages/substrate/src/fungible.ts [hunk 8]
```diff
@@ -100,22 +107,56 @@ class SubstrateFungibleAssetTransfer extends BaseTransfer {
...
+  async verifyBalance(): Promise<void> {
+    const fee = await this.getFee();
+
+    if (!isValidAddressForNetwork(this.sourceAddress, Network.SUBSTRATE))
+      throw new Error('Sender address is incorrect');
+
+    // Native token balance check
+    if ([FeeHandlerType.BASIC].includes(fee.type)) {
+      const amountBigNumber = new BN(this.amount.toString());
+      const { data: balance } = (await this.sourceNetworkProvider.query.system.account(
```
Comment (saadjhk) [inline packages/substrate/src/fungible.ts:119]: can you use a function for fetching native balance on substrate

File: packages/evm/src/fungible.ts (hunk 7 above)
Comment (Lykhoyda) [reply packages/evm/src/fungible.ts:231]: Here we apply for both scenarios if it's Basic and Percentage

File: packages/substrate/src/fungible.ts [hunk 9]
```diff
@@ -100,22 +107,52 @@ class SubstrateFungibleAssetTransfer extends BaseTransfer {
...
+      const amountBigNumber = new BN(this.amount.toString());
+      const balance = await getNativeTokenBalance(this.sourceNetworkProvider, this.sourceAddress);
+
+      if (new BN(balance.free).lt(amountBigNumber)) {
+        throw new Error('Insufficient balance to perform the Transaction');
+      }
+    }
+
+    // Transferable Token balance check
+    if ([FeeHandlerType.BASIC, FeeHandlerType.PERCENTAGE].includes(fee.type)) {
```
Comment (saadjhk) [inline packages/substrate/src/fungible.ts:127]: same as EVM

File: packages/evm/src/fungible.ts (hunk 7 above)
Comment (saadjhk) [reply packages/evm/src/fungible.ts:231]: in `BASIC` fee is not deducted in `erc20` so its not needed

**Review by saadjhk — APPROVED** [review]

**Review by wainola — APPROVED** [review]
